"""
Django settings for educa project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6kjk%*xzvrf8)+4mdg5$id08br_p0w+1-a6*(e3j49_x@jz@g^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'students.apps.StudentsConfig',
    'courses.apps.CoursesConfig',
    'embed_video',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'educa.urls'

#redirige al lista de cursos cuando cualquier ususario inicia sesion
#LOGIN_REDIRECT_URL = reverse_lazy('student_course_list')

# Redirige al usuario a la vista inteligente después de loguearse
LOGIN_REDIRECT_URL = 'smart_login_redirect'

# Opcional: a dónde ir cuando cierran sesión
LOGOUT_REDIRECT_URL = 'course_list' 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'educa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'  

TIME_ZONE = 'America/Santiago'  # Zona horaria de Santiago de Chile

USE_I18N = True

USE_TZ = True 

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

## configuracion para subir archivos multimedia
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================================
# CONFIGURACIÓN JAZZMIN - BOMBEROS EDUCA
# ============================================
JAZZMIN_SETTINGS = {
    "site_title": "Bomberos Educa Admin",
    "site_header": "🚒 Bomberos Educa",
    "site_brand": "Capacitación Bomberos Maipú-Cerrillos",
    "welcome_sign": "Bienvenido al Panel de Administración",
    "show_sidebar": True,
    "navigation_expanded": True,
    
    "icons": {
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users-cog",
        "courses.subject": "fas fa-book",
        "courses.course": "fas fa-graduation-cap",
        "courses.module": "fas fa-layer-group",
        "courses.quiz": "fas fa-clipboard-check",
        "courses.quizattempt": "fas fa-chart-line",
    },
    
    # Link directo al Dashboard (sin depender del admin site personalizado)
    "custom_links": {
        "courses": [{
            "name": "📊 Dashboard KPIs",
            "url": "/admin/dashboard-kpis/",  # ← URL absoluta
            "icon": "fas fa-chart-bar",
            "permissions": ["auth.view_user"],
        }],
    },
}